// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.Datas;

#nullable disable

namespace SchoolManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326033236_updateApprovalTablev2")]
    partial class updateApprovalTablev2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagement.Models.Award", b =>
                {
                    b.Property<int>("AwardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AwardId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GpaId")
                        .HasColumnType("int");

                    b.Property<int>("RequireApproval")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AwardId");

                    b.HasIndex("GpaId");

                    b.HasIndex("StudentId");

                    b.ToTable("Awards", t =>
                        {
                            t.HasCheckConstraint("CK_Award_Status", "Status IN ('Approved','Rejected','Pending')");
                        });
                });

            modelBuilder.Entity("SchoolManagement.Models.AwardApproval", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<int>("AwardId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("decision")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ApprovalId");

                    b.HasIndex("AwardId", "TeacherId")
                        .IsUnique();

                    b.HasIndex("TeacherId", "AwardId")
                        .IsUnique();

                    b.ToTable("AwardApprovals", t =>
                        {
                            t.HasCheckConstraint("CK_AwardApproval_decision", "decision IN ('Approve','Reject')");
                        });
                });

            modelBuilder.Entity("SchoolManagement.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Credits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseName")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SchoolManagement.Models.CourseSemester", b =>
                {
                    b.Property<int>("CourseSemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseSemesterId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.HasKey("CourseSemesterId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("CourseId", "SemesterId")
                        .IsUnique();

                    b.ToTable("CourseSemesters");
                });

            modelBuilder.Entity("SchoolManagement.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseSemesterId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseSemesterId");

                    b.HasIndex("StudentId", "CourseSemesterId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("SchoolManagement.Models.Gpa", b =>
                {
                    b.Property<int>("GPAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GPAId"));

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TotalCredits")
                        .HasColumnType("int");

                    b.Property<double?>("gpa")
                        .HasColumnType("float");

                    b.Property<string>("rank")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("GPAId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StudentId", "SemesterId")
                        .IsUnique();

                    b.ToTable("Gpas", t =>
                        {
                            t.HasCheckConstraint("CK_Gpa_gpa", "gpa IS NULL OR (gpa >= 0 AND gpa <= 4)");

                            t.HasCheckConstraint("CK_Gpa_rank", "rank In ('Excellent','Good','Average','Bad')");
                        });
                });

            modelBuilder.Entity("SchoolManagement.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<double?>("FinalGrade")
                        .HasColumnType("float");

                    b.Property<double?>("FirstGrade")
                        .HasColumnType("float");

                    b.Property<double?>("SecondGrade")
                        .HasColumnType("float");

                    b.HasKey("GradeId");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.ToTable("Grades", t =>
                        {
                            t.HasCheckConstraint("CK_Grade_FinalGrade", "FinalGrade IS NULL OR (FinalGrade >= 0 AND FinalGrade <= 10)");

                            t.HasCheckConstraint("CK_Grade_SecondGrade", "SecondGrade IS NULL OR (SecondGrade >= 0 AND SecondGrade <= 10)");

                            t.HasCheckConstraint("CK_Grades_FirstGrade", "FirstGrade IS NULL OR (FirstGrade >= 0 AND FirstGrade <= 10)");
                        });
                });

            modelBuilder.Entity("SchoolManagement.Models.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SchoolManagement.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("SchoolManagement.Models.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SemesterId");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("SchoolManagement.Models.TeacherCourseSemester", b =>
                {
                    b.Property<int>("TeacherCourseSemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherCourseSemesterId"));

                    b.Property<int>("CourseSemesterId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("TeacherCourseSemesterId");

                    b.HasIndex("CourseSemesterId");

                    b.HasIndex("TeacherId", "CourseSemesterId")
                        .IsUnique();

                    b.ToTable("TeacherCourseSemesters");
                });

            modelBuilder.Entity("SchoolManagement.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SchoolManagement.Models.Admin", b =>
                {
                    b.HasBaseType("SchoolManagement.Models.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("SchoolManagement.Models.Student", b =>
                {
                    b.HasBaseType("SchoolManagement.Models.User");

                    b.Property<int>("EnrollYear")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Student_EnrollYear", "UserType != 'Student' OR EnrollYear IS NOT NULL");

                            t.HasCheckConstraint("CK_Student_NoSpeciality", "UserType != 'Student' OR Speciality IS NULL");
                        });

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("SchoolManagement.Models.Teacher", b =>
                {
                    b.HasBaseType("SchoolManagement.Models.User");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Teacher_NoEnrollYear", "UserType != 'Teacher' OR EnrollYear IS NULL");

                            t.HasCheckConstraint("CK_Teacher_Speciality", "UserType != 'Teacher' OR Speciality IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("SchoolManagement.Models.Award", b =>
                {
                    b.HasOne("SchoolManagement.Models.Gpa", "Gpa")
                        .WithMany("Award")
                        .HasForeignKey("GpaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Models.Student", "Student")
                        .WithMany("Award")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gpa");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagement.Models.AwardApproval", b =>
                {
                    b.HasOne("SchoolManagement.Models.Award", "Award")
                        .WithMany("AwardApprovals")
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Models.Teacher", "Teacher")
                        .WithMany("AwardApprovals")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Award");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolManagement.Models.CourseSemester", b =>
                {
                    b.HasOne("SchoolManagement.Models.Course", "Course")
                        .WithMany("CourseSemester")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Models.Semester", "Semester")
                        .WithMany("CourseSemester")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("SchoolManagement.Models.Enrollment", b =>
                {
                    b.HasOne("SchoolManagement.Models.CourseSemester", "CourseSemester")
                        .WithMany("Enrollment")
                        .HasForeignKey("CourseSemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Models.Student", "Student")
                        .WithMany("Enrollment")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseSemester");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagement.Models.Gpa", b =>
                {
                    b.HasOne("SchoolManagement.Models.Semester", "Semester")
                        .WithMany("Gpa")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Models.Student", "Student")
                        .WithMany("Gpa")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Semester");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagement.Models.Grade", b =>
                {
                    b.HasOne("SchoolManagement.Models.Enrollment", "Enrollment")
                        .WithOne("Grade")
                        .HasForeignKey("SchoolManagement.Models.Grade", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("SchoolManagement.Models.RefreshToken", b =>
                {
                    b.HasOne("SchoolManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolManagement.Models.TeacherCourseSemester", b =>
                {
                    b.HasOne("SchoolManagement.Models.CourseSemester", "CourseSemester")
                        .WithMany("TeacherCourseSemester")
                        .HasForeignKey("CourseSemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Models.Teacher", "Teacher")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseSemester");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolManagement.Models.User", b =>
                {
                    b.HasOne("SchoolManagement.Models.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SchoolManagement.Models.Award", b =>
                {
                    b.Navigation("AwardApprovals");
                });

            modelBuilder.Entity("SchoolManagement.Models.Course", b =>
                {
                    b.Navigation("CourseSemester");
                });

            modelBuilder.Entity("SchoolManagement.Models.CourseSemester", b =>
                {
                    b.Navigation("Enrollment");

                    b.Navigation("TeacherCourseSemester");
                });

            modelBuilder.Entity("SchoolManagement.Models.Enrollment", b =>
                {
                    b.Navigation("Grade");
                });

            modelBuilder.Entity("SchoolManagement.Models.Gpa", b =>
                {
                    b.Navigation("Award");
                });

            modelBuilder.Entity("SchoolManagement.Models.Role", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolManagement.Models.Semester", b =>
                {
                    b.Navigation("CourseSemester");

                    b.Navigation("Gpa");
                });

            modelBuilder.Entity("SchoolManagement.Models.Student", b =>
                {
                    b.Navigation("Award");

                    b.Navigation("Enrollment");

                    b.Navigation("Gpa");
                });

            modelBuilder.Entity("SchoolManagement.Models.Teacher", b =>
                {
                    b.Navigation("AwardApprovals");

                    b.Navigation("TeacherCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
